### ISSUE TITLE
Module fails to install in Presta 1.7.7.2

### ISSUE THREAD

**Issue by Quebert90** [Invertus/saferpayofficial#11] opened 2021-02-27 19:40 UTC
Trying to install the module as described in the readme file but getting the below error. 

I saw a similar issue on the mollie module (#252) which seems to be supported by Invertus as well. Maybe the issues are related. 

`Compile Error: Declaration of SaferPayOfficial::getContainer() must be compatible with ModuleCore::getContainer(): Symfony\Component\DependencyInjection\ContainerInterface
[Symfony\Component\Debug\Exception\FatalErrorException 0]`

Debug menu lays out that the issue is related to the following function in the saferpayofficial.php file (line 114):

`    /**
     * @return mixed
     */
    public function getContainer()
    {
        return $this->moduleContainer;
    }`

If there is a hotfix until the issue is resolved in a new version, please head me to the right direction.

Thanks

**Comment by yvannb** [comment] 2021-03-16 17:14
Same issue with Prestashop 1.7.7.2 with PHP 7.4.16

**Comment by Saimis777** [comment] 2021-03-24 16:09
Hello, thank you for your messages!

Have you tried removing the module completely from Prestashop files, and re-installing it? If yes, did it solve the issue?

Let me know!

--
Best regards,
Invertus Support team

**Comment by Quebert90** [comment] 2021-03-24 16:21
Yes, multiple times actually. Did not resolve the described issue.

**Comment by brunostuder** [comment] 2021-03-26 13:54
Hello!

I've the same error there, did any fix as been found?

Best,

**Comment by Saimis777** [comment] 2021-03-26 16:00
Hello community,

Yes, we're going to upload the updated version if everything goes right this weekend, if not - next week.

You will find it in the same repository.

Thank you for your patience!

And have a nice weekend!

--
Best regards,
Invertus Support team

**Comment by fabi86** [comment] 2021-03-29 10:28
Thanks, would really appreciate it. Waiting for the module to launch a new shop :)

**Comment by Saimis777** [comment] 2021-03-29 15:45
Hello fellow users!

Please find the latest upload in the master branch - https://github.com/Invertus/saferpayofficial

Let us know how it will go installing it! As we've tested everything seems to install and work as it should!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-04-08 14:34
Hello Community,

Is everything working as intended? Did the installation went on succesfully? If yes, can I mark this issue as resolved?

--
Best regards,
Invertus Support team

**Comment by Arthur1965-13** [comment] 2021-04-16 10:13
Hi 

I wanted to upload today on prestashop but it seems there is some error
Sending you a screen of Debug Error

![Capture d’écran 2021-04-16 à 12 10 56](https://user-images.githubusercontent.com/81377460/115009802-f7917280-9eac-11eb-84a5-c3ed0cf36db6.png)

Best Regards

**Comment by Saimis777** [comment] 2021-04-21 12:24
Hello @Arthur1965-13 ,

Did you follow the read.me instructions on how to properly install the module? You can find them here:
![image](https://user-images.githubusercontent.com/75423142/115553081-ac64ce80-a2b5-11eb-8a95-1a143c6b38f5.png)

Let me know once you've followed them, and if everything works!

--
Best regards,
Invertus Support team

**Comment by SimonasB88** [comment] 2021-05-14 14:56
Hey guys, 
Have you manage to grab the latest module from the repository and try to install the module? Or we can close this ticket for now.
---
Best Regards
Invertus Support Team

**Comment by Quebert90** [comment] 2021-05-14 15:10
I am not able to test it, since I moved to a different plugin in the meanwhile. Maybe someone else can confirm?

**Comment by Maz-Invertus** [comment] 2021-05-17 09:30
@Arthur1965-13 @yvannb @fabi86 @brunostuder could you provide us feedback if new module version has solved the reported issue?

Looking forward to hearing from you,
Best Regards
Invertus Support Team

**Comment by Saimis777** [comment] 2021-06-11 08:31
Hey,

Due to inactivity, I will close this issue for now, let me know if further help is needed!

Any feedback is greatly appreciated!

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-06-11 08:31 UTC

**Comment by powolnymarcel** [comment] 2022-04-08 09:16
Hello, 
Same problem on PS 1.7.8.5 
<img width="544" alt="image" src="https://user-images.githubusercontent.com/12711039/162405463-67030b84-1c58-4a5d-8779-58b78cab6006.png">

**Comment by Saimis777** [comment] 2022-04-11 07:34
Hi @powolnymarcel ,

Please try using this version of the module that I've uploaded for you to download - https://ufile.io/30j8b9jg

Let us know if it works!

--
Best regards,
Invertus Support team

**Comment by powolnymarcel** [comment] 2022-04-11 07:47
Just tested it, Works fine
