### ISSUE TITLE
Authorization Problem

### ISSUE THREAD

**Issue by Shoprunners** [Invertus/saferpayofficial#142] opened 2024-01-12 09:58 UTC
When trying to pay I get this log entry.

LOG Entry:
Request:
{"RequestHeader":{"SpecVersion":"1.32","CustomerId":"*****","RequestId":"ps-********","RetryIndicator":"0","ClientInfo":{"ShopInfo":"PrestaShop_1.7.7.8:Invertus_1.1.7"}},"Token":"*****","RegisterAlias":{"IdGenerator":"RANDOM_UNIQUE"}}

Response
Initialize API failed: {"ResponseHeader":{"SpecVersion":"1.32","RequestId":"ps-****"},"Behavior":"ABORT","ErrorName":"TRANSACTION_IN_WRONG_STATE","ErrorMessage":"Invalid action","TransactionId":"****","OrderId":"****"}

error in frontend:
"We couldn't authorize your payment. Please try again."
Is this an API problem or just the response, that there is problem with the payment

The buyer can do the Mastercard 3D secure workflow, but this is on the end after doing this.

**Comment by justelis22** [comment] 2024-01-12 13:08
Hi there @Shoprunners,

We will check this issue and get back to you as soon as possible.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2024-02-27 11:35
Hi there @Shoprunners,

The issue is fixed in the latest [1.2.1 release.](https://github.com/Invertus/saferpayofficial/releases/tag/v1.2.1)

We will be waiting for your feedback!

Best Regards,
Invertus Support team.

**Closed** 2024-02-27 11:35 UTC
